---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpn
  namespace: network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vpn",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.56",
          "mode": "bridge",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }