---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app garage
spec:
  interval: 2h
  chartRef:
    kind: OCIRepository
    name: garage-app
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      garage:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: dxflrs/garage
              tag: v2.1.0@sha256:4c9b34c113e61358466e83fd6e7d66e6d18657ede14b776eb78a93ee8da7cf6a
            envFrom:
              - secretRef:
                  name: garage
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: *app
        ports:
          api:
            port: &port 3903
          web:
            port: &webPort 3902
          s3:
            port: &s3Port 3900
    route:
      api:
        annotations:
          gatus.home-operations.com/endpoint: |-
            name: Garage S3 API
            group: storage
            interval: 1m
            urlPath: /health
            conditions:
              - "[STATUS] >= 200 && [STATUS] < 405"
        hostnames:
          - garage-api.00o.sh
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
      s3:
        annotations:
          gatus.home-operations.com/endpoint: |-
            name: Garage S3
            group: storage
            interval: 1m
            urlPath: /health
            conditions:
              - "[STATUS] >= 200 && [STATUS] < 405"
        hostnames:
          - garage-s3.00o.sh
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *s3Port
      web:
        annotations:
          gatus.home-operations.com/endpoint: |-
            name: Garage Bucket Web Access
            group: storage
            interval: 1m
            urlPath: /
            conditions:
              - "[STATUS] >= 200 && [STATUS] < 405"
        hostnames:
          - garage-web.00o.sh
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *webPort
    persistence:
      config:
        enabled: true
        type: configMap
        name: garage
        globalMounts:
          - path: /etc/garage.toml
            subPath: configuration.toml
      data:
        type: nfs
        server: nas.3226texas.com
        path: /mnt/Speed/Kubernetes/apps/garage/data
        globalMounts:
          - path: /data
      meta:
        type: nfs
        server: nas.3226texas.com
        path: /mnt/Speed/Kubernetes/apps/garage/meta
        globalMounts:
          - path: /meta