apiVersion: v1
kind: Secret
metadata:
  name: garage
stringData:
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:cLT5L4YI9uSEoy0LoAbljUrdv6JESxQrOr0S9SelVa9uaSe7GUUTp1kHag==,iv:vRcidfriONHdsVALHvYfa4cIDTMqYKkSa+b1bRKoTbc=,tag:ips9R5jpSgnWJB4OLM6mvg==,type:str]
  GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:pdv2mMhDn5ufLNJOXQ/Bbb9gAEbKjNxir8gzKVzb8Fm4Jj70SfF7K8s6J5b+ryi1,iv:8xwmKHGdLWg9OCNHpIS9lgvv9oUWDt/djn9I51KTJrg=,tag:3A7bJv/UxEvTNn+Y9Jo8pg==,type:str]
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:pN+TURWx6QNiAvDGkVrSAD9ZZzvu7v+vi3UQGxDILc8XINIkj3ZtfhOWKJivVMiYFmn9YP4QlrAPDBBvfNxErw==,iv:pd45WcbxLAoxHNdg62kJcKlspy6ghaCiHjVIblf6g6k=,tag:o2NkdjxBVxyx41RkaSArUw==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZTJFRExPUml2TjF6WHBx
        MVdpdU9KQWg3MHFudXN3VWN2dzJ5SFI3WHprClZ6UE01UXQwVjhYZjlkdHJHemRV
        WHdib1ZlZnFQZnVsWk9BMWd4K1JvRUkKLS0tIExVdm9CSG9nUnV1anI0c0h2NUhX
        dGJFWXIvY0hFL3BjYjVMTUlPTGdGTFEK40v8I30gAXEphUfWi1ZryJa/4FZWWCnZ
        jaEhDcNID2a2r1+Y76xoihfvkCwcmuo89THpRFTvuN3R2vMghczxKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:56:52Z"
  mac: ENC[AES256_GCM,data:YruIY4oj8pNyebvpT1eTIW/Qk8R8FPxcX6JH8IpbBlqYxWOeynTO7iA2GZXBVgvN+x14XDmYu8xfoLNDyHZ+eLDUFjeSiOHbfI6Y/s8MmajZReFcLjUpvKJqABhXRB6H5D51YXyKkC2A5xR+y+3mAKA9/H9X9hAIoM02dy7meVM=,iv:+WKBSe2NgsFnDEI7q8YLk5tNoIPx9NFKkOOYqifGEHY=,tag:ZmE2hV1S1Kolf145S9VbTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
