apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:bm8mXjRcgEn3E6A27NzipvpP5qtJnGVH3QTJyFRT0p0QHMiBUeNznQ==,iv:C3Alp3bb0eKSS0d/jwYhhLentBdKdzVZBN3RLRCSbGQ=,tag:UQFDRyviqSp4x2q8rKznQQ==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYy9NODFzYk1ZaVc1ZEZ3
        V21IZTRoU1cxYi9qWklxemE1eWo5NHo1U0d3CjZONDkyYWkwVFI3ZkVITEFIN0k1
        cjVCTTNFOUd6VElDTndtMXZINzVDV0kKLS0tIGhaWkxFTUczakY5NUloMjJTOUlq
        VG5LcjdHUitoRlZXTXZsVS9hMFFSYzQKG9lqJPozBztnUthr7kcxtUmanPz7NfTq
        gkZlPgFg9jMX4aYpvmY29ztUj8R5DMS+qtoikl7jqMnvqaQNK3+Igg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:07:21Z"
  mac: ENC[AES256_GCM,data:+1eb50pI3R9Vayt7I6fCyJBK4UvCLHDK2iFG+umbbmR4nGHOjPvsa7R3kGfOrpAnpBOM4HGoBT/++oaSzf+W6DEbDPRkl1PdboW3+l/T/b+UH+Rl2xWQucjLi90t+241nBzs9WP9t60ussByeo3PCv0gkFfYAzFI//j7E5YTHw0=,iv:MbbMbnUF580Po9KEchxlEb0DMJ8Ufb8//Y7nj3ECbRk=,tag:I6KtsPmqmr6C6T9HLsWc2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
