apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:S9rgZzZ51ntksy3R0S2EohEaqao8WwJB5TlKJfO6V6rkw0etJsmUzw==,iv:rX8MJ7bOoIO5sLi9MWYNVQgMKzfYQNwiUGekOtsoKZE=,tag:k1VYVZuKWzFXN72GwCEkRg==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT1ozbVdVRG1aWXhJQzVo
        a3BZUWY0bExEellqK3htQy9Kb2hnbklmZ2wwCmsrb0hiTVFmNnAzSkFuOENRMWpm
        RnRCSVoyaFRZTEhkZVNkTU5kV1FDemcKLS0tIGUwdFZjeU1HUHlGUDRFYUh4L2FO
        SkRiMmJRVjhaYkc4QVcvNVh0NWVQWmcKx6WVsV/rO+y9NHh0SdubJmO3q9zO75Ym
        2s8W9sFVeej2PlzSfzlFtlJD3DkT2PbJ3bKoRV1qED97Xd3L7335mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T23:07:05Z"
  mac: ENC[AES256_GCM,data:/lC3VkVCQe4Y5dPHa6AG8b92TwC1aM1CcuK6HQ6PFsSQ+bRJS/h8ldhMgF74pX2ebOtKJ4RbALKVdipmbZbkNhwmNfw0RDM0xwgAGK4cj7HfK6norRXB4sXeyLiIL42ET5bMMgsuMDLCnvKvTQh1mWCplSqU82EY0xdq14LzHDU=,iv:TGEs80kFOqKIbILLHAQExx0yBWf6XhYfRI7oUw7/2Aw=,tag:e9LT/h797+Tb+RlLwC1x/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
