# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
type: Opaque
stringData:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:yuv1/8u2Sa3hLmo=,iv:RgmtGk6OIMeMBFpoc3OsfDbxhSenNJ5Jusb9BXUk2Yk=,tag:snt1AOEZD/WjVeTyZEPTtQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:+xeI8Oqa3AXXJg==,iv:nVAAun9d3zJ5JZY9CO1g7TU7RVNI9qUAfJ3/Nymh9aM=,tag:3P+4u80Kgze1UDwQUsjhIw==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:+7K+nfBJYkFtXVdyvpyi0JnQil3JzdgK,iv:TuFhgeSvCNRzYNDOVO3St4e7u4ogCPGGb43Z/UsTWAo=,tag:hsXwBgp39dVsSoo/J/RolA==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VDRmdUV2eWhNU2Q5TExP
        UWlrNExlOFdJRGVCZUl3aWtzVWZJNitVMW5BCnNCTVY5Rkl2U0d6S0hQSXJYWFAz
        SmFTaTMxSmtkUXJPa0djNldQR3ZGK0kKLS0tIFU2ZUlCSmFxM2Qxa2lxNFdiNy9Z
        SERFRHQ1d212Ukl3R1A2UGJvQnByRXMKsjAsdOaEm6QfEU+vyQuDO7jCjKAPosyc
        dJh4QfBvR57AgvdFtD767H9DqnoPh+rHdcLtSYJGWUbjlfwqaXw6TQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T23:48:10Z"
  mac: ENC[AES256_GCM,data:+8oNUAZG7PUZgkEz6fB76PzRnxmBal2re/7p3uW581R2y8mhlSbBQZ8QgXo52sk1m34o7H4g2ozlZYjul/wE1B+ZpONTcyDFpE1Q830GioxWMpzpTHcA9LHBzgGQ8uHCLEBw13MLH93Nk/M1ZifhmZO+WNcwUaws0x1IPW0r0Uc=,iv:x2LFTjTeV++6z8Sk3rQ3JeXkj5sOhflj0iX8AgykwP4=,tag:LkEo9LkF53QgAqJ4JhTqLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
