apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:0P1mnkzz,iv:h1/7lrmK2A6gssULvawheohgSKvNGXpAP7BPxI+I6A0=,tag:F7hRCZEBHT6CAgAd9x+hsA==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESTZQTzFITlROY3FYWUxx
        S2l2WE1tM1VRM0g2b1ZEdmkrcFlLQXBOcEdjCnFLb1kyU2x2K0VTakMvQkxrUmdW
        RXZXemhiRmRRVzBIWE9LTUoxWjJyTHcKLS0tIExFZzhBaVdGamJhSEtHVWM5cWtI
        TVF1bkw4TjlkTzBaNHZLaUpseDlJY2cKokCOi0dJ21SSO6DE86NvxmJycxZzEvCG
        Qxa9UXni0LencurypNpOZzTCyqec4YGXDMILS0ANhGAlR6KW8ZSBhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:29:41Z"
  mac: ENC[AES256_GCM,data:324Z9WDFodm/AeVp44xhowxRsQXXSp9C9wVSELilGSPT6UZDW3DaE98SpDvVQ5ua09g6Id/mBM59BLhxILzYhWl0t3FZmVZZoSuT/O6VbqmbEQXjIIJ99L9y6tIY1gCMW1gwpb5LDentLU13ABBzGJFxRQ9WTalrrXecmcURhN4=,iv:wL4RucfnrPD7Yx4Ba0rHjZN5m/pj9TFGsIwWzBNIa18=,tag:W1c/DVvJUn63X8h8+c0vYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
