apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HyLp8Euz,iv:09MGCvcDH2TDOU4smYj7gFDtRVbiQJXxLJCySo5clhU=,tag:eLWBUlODciBSaLDA5PDcqg==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZ0lIdFFMaXZZckZkdkJo
        d1hsc3M0b0dTNWNuWVFXbUNya01qWUlJNFdnCjBpOW5ETmVXWWZDejhrdzdrREZG
        YlZwczc5ZktOQmRta3dIMllIdExNSEkKLS0tICtSMFpqdU5QMVBETUNIL3JiNUdH
        R3BjS0hXNWpwSG9UMGd2ZGZrQ2tDQWsKJJ4O5cKg3HCPh2hTRprmkdiQDf3wqh+s
        9AdSrS96iBUltNSEJE6VF4+GwF+3azXiAH8lwnXOeNF/fhseeIWrBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:07:21Z"
  mac: ENC[AES256_GCM,data:ngeAXJx96uTqrCMXJhexROtwQC8CMQN9Effg3TFNo7AMWZhu+aOntQja+PvOZrJ0GggOGyEzildHBJIuiN68DcBLgZyQOQLO1Wmpr9KBvwu3KEYphIK/MOvqzwNH+GU2AeOxbfgC/y3Ykqmx8f5youPSTLnYwUJndMxmFzi+e48=,iv:Bf8E2uRLC5Nc8HkwOh6hfvNPh5sx4EjNDvYDeFCqGgE=,tag:/Es08Z31Ll0DwapJt2M2Kw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
