apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:pgmS8grW,iv:mjSi/pVPveqqz0nYC871gvvOIATiORXA38TKar8ad90=,tag:Q30ZfdUCbSST9Qay5FrcWQ==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMEVEN0ZTb0NVWkZodStx
        TEhGRGcrTFo3enZDZGgxQ3dDUHBpUUlSNG1FCm9aUjhXVjE0MnNid0d6eEMrUFNP
        SWtUUE1rUE56ZXBta1RZWnNLVkxlQVkKLS0tIElJbWpwTzZjQWFrRUVjRGIwS3A4
        TWYwbkI1YzBGNWdTWldUV2pUU3VrdlUKNDXsqc7f5aWjgNUK4nGWg6DOYZppXvPc
        6DlrcyVGlq4WCWu/CKV7OVtGhlikGnQuoL8LKAtE3MECCYM8CcED0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T23:07:05Z"
  mac: ENC[AES256_GCM,data:eWvxK0+q1nZ4D1JxL1tMciLBQ+bTKqTyPb+Yvo2Wt7mCbMlo9rg/Zf9ed7O0UO1xZEHQj+bozZs08qI6trYqkYhT0IcCX9S7wFtfY30QC9gexFuRD9wJSgRd7Yh7kTiVU1HdT5xWyGw1W22Z1HkjA+/qS/ZSZdO75C07jRiPNQk=,iv:YgmoTDHXI3aDbAfUaqJac7ABHwmIVZbObsGpeNOSi6k=,tag:VJudkQAw61nIjDDMkSinWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
