apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:/ZcLeeU60HxJI6BRuzOuvdgRAM83cmZpbPgTLifKUYw=,iv:wl4F08sVHNM2+rBPt0wP7SUjzfoqiR73ooniYIubaTo=,tag:irQB6g4A0HVSnzJ8+2QWbQ==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bWNheGdpT1UxM01ZZ1Bh
        aU5rODJZZm1lbDE5bVI4THByTkloZHM4a2c4Cm4vekdMMkxIWk9GVlJRM0IxeTlm
        V3M2M1BIMHlOR3pCV2Z2WnowTlRLSmMKLS0tIE9iS2lTemlaTkJYb2ZHay9HaTNT
        TVpvMERIUCt5N21iT0QyMTN3OUcwTW8KZcs1T+xOJY06uJWUHSMYPIqUVmpEPpgx
        q0OIl14M2DofGDoMblm4Jlh0ON90IK4eODjjF7v1Jkw3bKMrAiT8fA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T23:07:05Z"
  mac: ENC[AES256_GCM,data:yzrOAO7RPsdupVmFRdw8cFnsJQ8RNvprXbTD4ltGQPkCL4FPkID+yPaQLbzaLKeJSVJSMjMCkBzobwTy2Ak8oMXKtaNZrNnD5/0SK+WnsmR+VUv92vMwCuNDTrnfem16q4Q/2NqQowvI0YyIWJdEZz/dOENbpN4pYKdb8+OFBl4=,iv:wSfSLKyZjYVBIlwon/V8fSfrtNYGKyZ0NnZfS5FnR68=,tag:A+DvdFTOl4gTVvNfzFRIEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
