apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:G8lJeQJYdZ7ZZn3NqSi332UbUi9mNDM/h/tI34hT9Ps=,iv:ueV66MKM3Qzt0BcbItogFppA1CedW0pGdIAC3prvEjA=,tag:dNIE7MxUCkE1a8eBsFB/iw==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcU01UHcrODVsbGJKczR1
        VXQ4bFRGUktQZkNYY3ZuSjFmZzVCd0NSMjE0CldyOUgzcndGSm4zVTkwSXJOR2RQ
        bmlnZlArR003dXRBY1dDd3h5Q25PVFEKLS0tIDNGUEQ4NjdXTUJvakttRW9OWnBE
        aUdwa01oRzZnN2JoZTRLU3NYM3dTRkkKiElYiriJR+UHFK0hMhwuE9qgPR0OgZ8E
        pNgBv6dpigangZVSWvGKiBRRQGyFsI8Is/CK8N7D/lMj/0B9vsYCiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:07:21Z"
  mac: ENC[AES256_GCM,data:E+l/yWSwrQ24FuS/dS9xE+Ut5ZJ0oeqa74k610gBYd1HeApylQZdAhPREPOBI7j4B5RztBB3WiSFGvg0pSs0o0gVBCtfpyisjng7imHZI3mQdoPUFcN1f0T8rFgW+2z5mZyucFYhFIJX4GvA+jnPkQzvLqq76hXLZBPNs4plpx0=,iv:XPgrGXVt/Ry9FYmTYbTUG9Z5nge3UaaeFReVFQe3Vpo=,tag:fIxvhH7ltXf62cPIaRdH7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
