apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:A3Wlt29F3GPPzZXEoP4DOF3HEccjK6hLyFKtOXt0YS0=,iv:LVXCykj+UILt4KJviVGPkIGOzWkaOpTrTbKKxW8wJzA=,tag:10mheBKlnWwtzU46b+A2rg==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNU05d256MkNhSFFFRGV1
        bXZwV3BXdlcrOUF3R04xNjQrM0xEQlMzOHhBCkFSK2Jpd1I2bFJEVXRpb1I2TGZv
        MTJ6SmZMaDBZdzF1TUkrN2xVWDJjWDAKLS0tIDgwREY1d01NdFBWdWpSYnZiaUlv
        UXFsR2xzWDNqcmtTbTlQSm1QdEtLMVEKGizjZ4i2SOcMF1NSKyWrOQVKITX0o4s6
        JsjnY7FchgEvhppq4SOX/zH0UwrwOyYAAGgF11BeznFJgsZQ3pNyzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:29:41Z"
  mac: ENC[AES256_GCM,data:nj6TbEtQU7SOMGlibSrsg5Kw696B6NUtnDtF74pYEACeLijH6jrXNxpIqTpBYytbw1agsp19N87Xgl6ibEty6YId5H7eagiLIA98hVbokYU13QzVZzYF+y1Wuz7pGHgTWYE0ljqUJ6A3qiWwSRPmy/CLX6Bpa+9KCvCD1HUV6PY=,iv:EKcNVfyYCDpijA4fqWjC6gXd25m9sVWUauVLYMuAx38=,tag:Fjt+qmJr6Gdu4aQFsaMOJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
