apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:fCxosYrPM1T6r2tlYz5rF/pH+5/WNuHRiENOz6bn9zJ87sY5b/CMwM9cRzQXlzAj9G5NJzSQIJP1BA2pIAg/S3f0z13f0ifVEh583eauvZdPfpB+AJRSgwSdlmZ95YQv6GEqfCnQvhImA1sIXlhoXNJWcRt3GCFsQvpihhgb88rCU/yEFCAETojiGFRk1TtohAAC1N0ftazsiIaE1FbSmA3Co70SO08KkrQaYZJQfcXo212+,iv:2yM12Y4ZsOv/Wz4sxKqBOOLhdj4iEz16Ebi6WhYKHRQ=,tag:23NP4LmPy68YaUT64dyNzg==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWazBnbHNPVnlsVFBnS0VF
        b2pSalloc2drY2ZzbnFRajJ0RzczZ05kRm1vCm5kcG1wY1JsWDkySXBjWElvYWtq
        TnFFMHdUQ0g1NTViUDBCRTZWMHBIaDAKLS0tIDVsZlpGTnZmNjZXM2x0MVdUQ3J3
        RFI1ZFJpUmpPaUFpY1h1UjdkWndXNWMKqxVxf34qbeolxYXS8FF6acWCj1jSS5ep
        5NAHDMo/WKiNes+Yc+RBM8qr761b3lhTg3s+j87kX/pmuztf9cEH7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T23:07:05Z"
  mac: ENC[AES256_GCM,data:oVbl9RXjj/CA2vu+Y3LPKN3l8b1fW4vs+mKCFB3e2Pby490maPgDPj1v0j0TT72OTj2qFEMYfdLXKwt4aSijGNU/MtlzH1BGwgaq61AAIZ0q2b8VRZTygY97SyawGAzWHxEYotMqxS9ewj7AyQlxg1hn9M63rw5aC8VhMk/Rjf0=,iv:r1cY84KC/Yx4i+hxZqwYbcjxVhUK9D8te1Vhpn1Hy5k=,tag:jX+YE4Sy+HQzMb3WZb6/JQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
