apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:pM1lsesFcWRfZVSMZUFav7JbyEwGFbTE5EMElkS3Kld+L39c5b3V6HxQjZbrWvV0SwYKIZaqRgWOtZw2thXGKLiwVi1UORA5OAmXInb29V+Tec09axD3lNR1SsYMlfxYDCN5BTVGxfDhff54eYKMFTZu+TnLKTeynzPWEYaN0OTWspy0rd9au7ND5g4gTQ9g+VV1G3XEPoyuAxWzg0JHjl6csicZW7LbjAN58wv8UdKdZkhB,iv:RRIdu+Qpxy40yycOIpWJYiA9g1EYXCilIEf8GRwa5xY=,tag:vPtoxIM3oeGVCCSWf8Ip2w==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUFdkQUVtMTlFYWk3S1I4
        VkMydVdYYzluemlaZTVsVjF0bVlNRDJuMGowCks1bURITGszWklSMyt0VFNSYmtV
        d0F4VlJWaTk2N0xENjJFaDMwZGpJTkEKLS0tIFRXMjQvSHEyYUhQNlJsK3dVbkNS
        TDJHUktnbnM1Tm1RY3ZQOVF1YkRiZXMKownqLqA5hnI5AyTP50Zyv5QDWK7BP9z2
        zWYjhh3qR4GxbpbkBxJmtyfx7HOYxmx4v9FxY+SVoJQSazxfah4MDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:07:21Z"
  mac: ENC[AES256_GCM,data:OuJzV4Hoz6s5yMBOsmcFKLhnQ6edwNksOh3bumatlCQyl4sFwUuEZiqF38tn4PUayIItLy7saVXzfR+/KYS9B0+XTr3/Bh3rfMx886vWs1t3s7rSY7l5ZVyjHGcjqRrqK7BVYOXTN2rGgN6qeI26fDxXFi0gJTEXvUuBKtFQMDc=,iv:FdvzBF4c5avjNITfbJm+Ck2iqQP+cv5zzSfXeUCCx0c=,tag:KvmDbj+Wv/fFJEw2x9IrlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
