apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Jy4wEQ5k2Hgi3CgHaaPpHmRdsWu8kumaadHF/ab+dXHGU0JITArrimm46JdJW6vsHVpAAs7qA2mH/hEgcTSefOb++fNeG1MRCKx1IkCGRu+s3EcyuxneNUt5T/te5oMIa4VkQjs3VqPzXNSLDKaZxVWk5EVFqWz3XcKgsOMKCRodUN25o5PsNGoXF2YTZ4WWpVl0ofl2I7JmLM7bRbR8hgrij+ThOF2Q0mrTV5rSzKxT3Z/S,iv:d+9Ui9fJegsJ1hAfzwOK9LpeIvelcPnwphxFGCKy46g=,tag:Z5KfMd9YkTVu3IfmK8DRug==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNHhQMGxoUU1ldVV5eGh4
        NGdLY24rWmVwS2FTT2tiU1RlcUNNRnNqbERjCjdxWjR4a083RTcxcnZUNXdjclRi
        T2lQaFhFMElScGFTRlhjb1J4dVBKTlUKLS0tIGtmOE5KbnhJS01zV2I4bEZ1bW5j
        eC9Ld3BtQ2JESnpYYXdiMmMwcFNCaVEKMHVBUEzaukYL/staxEo8mjWQWsP/9FDA
        JfXtmsacXbozumUffe0n6mfdx0UcB/Vb4fb36P43lclMZICqIHNXSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:29:41Z"
  mac: ENC[AES256_GCM,data:1XROGwUyH2/aoNplau+H1faNv/l4hjTfS9k7t7J4ESejNS8xn3nST/F3u91qf+CJ6J0c9IlkiALd/rymq+03a7ic/UipcVWD8aAQWQ4OB1B/PEBgJU1PTCT0ZsRFeHVZqZalr1jxFCa0dPQakOZ1ysdnP4k5wdoRycGsU7j+hag=,iv:h9bFzcDuSetpWiyT+yHBqcd1F5G9YeFTerhaSBIA+kc=,tag:a//RG6BUOU86+QpK3zRTEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
