# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:h4Tj58edNEwtbsWGvWI8aRTH44ELzWanaNsFw2nP0u8=,iv:FvqGNPbI28Vy/cW+oGdJbBgZdK/XE3kq5bRAX7Y/sck=,tag:5YV1TyZ8OkNgolpe+3/+NA==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y0xIMHE0bGxSVnpCclNX
        aWgyMWlXWEMxR3RMWk5KczA2bWM5QXliaHhrCisvWThFeFI0bVNCSE15dWIyT3dC
        Q0VDTDMyOEZRMXFSSEp3SnF6ZWNRNVEKLS0tIDdqTGc3enpFWGlJbCttT1ZEWFpF
        YUlDdVdzVFh2VjMzMGRCRmhGUnA0eE0Ky0DUpyKyaBJmbtLFKLmaHgK6jItZezSH
        TP1ekir8rCKmq9dDuHUtV1Bi2yffG0XelVCzqsd55bpHS++Ld8VMxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:50:26Z"
  mac: ENC[AES256_GCM,data:yxoFlDK0VKhlWSO60j/0S9524YcpcoLO9ad4moRz3ztB28MW02j8jn3BbATzr0TRuY8uT10wSB+iWfiat55R3wHiwkM54ooaKXMn8L1CcZh9IbkGmgpr0k8An/MibjgE7cQTKDMXpY6eoTYIIU//T7UA3vplhbYnc37NfUkU9iw=,iv:BS+llT7UdnXv+aaAjrxfAFVZ8ArAy6MqRrIiIxhq6aw=,tag:bH/K2ZrFmYD9IJa3ihlvxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
