apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:X6VVYu6mcND1yUcF7CzJvWmkIkeFyDmyZG6ogbI5YYEDTboFhFMvGQ==,iv:yUqfElaMevvIZ1hLt1liTu7GWuyYvYNn5uskTeTO4YQ=,tag:K5st4OO7dw/Fy8SlMlNeFg==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibHNtVjhsTFdzNHRRUUJv
        ZnJzbXdSdTlTWC9Dd1hBdFQ1SzgzNW4yQXpjCjVlVWNMOW1SYkkvQ2l3Vk5USXc2
        akl0eThGNUdieGZCazdlV1BTa2RyaTAKLS0tIHl3a3g0Tm0yQTdrRVcrZVRrVzB0
        ajFCOXF2UXpWZzlBV3J5TmVrWjZMbjAKLZ9NUtoO3nvPVq3RJhS6+87iZBo5SmM5
        cqD8v2SduepTOnVeDXEf6R4us8SY1rDQk0j/ye6FcVFIezDXo4Ty9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:07:21Z"
  mac: ENC[AES256_GCM,data:eIzLpfMyZVBjuz7i2LgRZsXonX9lDFhz2U0U8UT8scVRhlloCC7wkeEOyV2BfNSalR8wmzYA38hR5SWmmzHaaHzXlrp5dpkVFKkwudESHB4q3rkjZjIpCf1miXo4BDgUE/xToTPU8qt7l7utkGr63sNBOyU+lCE323Ebnz+dbSA=,iv:xVIyxAIZuivBfPJgUtr+tlTaac2ZzjBYXIXmjWzfGnw=,tag:W2QOvEQgRQrzhI35aa7ImQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
