apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:8iIsaekukuv0ZndevAPtldm8uk8J1SrsZnJQrxtRwDRwduOsXBLwyA==,iv:cWyT0ZWycR7FZwwZG+nsUKlI7zxH5YTA6Zs3z+HMziU=,tag:ITQnlSP68fi3r6HR6ngudw==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a0ErUlk0OWZCNy9kTGYv
        TFVuM3N4MTJ2VlBNWWxNNmZ3TDZ1cmQ2QmhNCklTdE9uR2ZweHNNRHdxVkR3K2Ft
        KzVCbXVnNzQvU0wzK0g4bVpxcHZGRU0KLS0tIEdJUit3cG4xVWxUazd1ZFdDL1lW
        M0tzNGYrNzNNaW1xMm9zc0FWS09aY1kKN+j9gKJeJJCfprj/E3hGfDC3W+gHhpeY
        ot+lEhe1U1trfgMypvd0FvuBjMjhFTvVZPEZlDTqFahPTJeyfmgKHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T23:07:05Z"
  mac: ENC[AES256_GCM,data:ny0gSYuSOxS0RoZYpAJivrOsTrnMmPjFR+egfftjLpaU8/oRaarxE6/2x3GosF7VCrMxLAC8HmcSxHJXo/XlAmazuzbECOnDSObjtJd9PV9MIwixvYkA/KUXXSUfKia3PypC3Tov6VszAKA5PCEsW4JGf7p7CKYcxm0lYHfMn7k=,iv:2Z8cvP+xjaahJYFiLKM+rvEVmVp6i9v4fDMm14vUJl4=,tag:b6X1ibgYQ/cZRnHvY80KQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
