apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ggLxFThNZKRlMhIpEy/pRJLRx+h7fDyltyxQNfv/+talKmytmSBAWw==,iv:sUEi1mJn0+B4611UwzAwXjhaHXE3YHx5buDyNlnCj70=,tag:gI+064+ncUhubhJWG4hupw==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeC9wRTI4OFIzSTY4U1Zt
        MWpKM2VPMS9jZ3FXMnB4WWY4cS96UUNZSW5nCmlHeldiOEsxaHFJa29URHgvQStt
        cExoaW9hZThKVE1obm5zYS93aHFXSTgKLS0tIDU1Y1RTNVZ6bzhrTmdPaW1xc2Zk
        enJpRDllWGNSSTdFR0RzcTYwem5BYlUKFvqe27ixvDPHKmYa7i5xsE60aOkI3EYl
        PV57f1n+zR5MJ2SIaiUX/Pxx5Wd+fMS0QiZxn/qtuwOgaE0SJFNYwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:29:41Z"
  mac: ENC[AES256_GCM,data:xrFHsQzsWZGtp4gdM7+C0Y49BQbvlgNC00lv6KCA2rO8g1U+YjsloUoU5lb4iw0c/dXv2yHL3lpR6GoS9Ho1TiRc/4F2gwhfbd7/yAJENX3htUzYtL4sJsRQ+aH75MKpX+WsktmdjAvfPE+0hmgS4BErOIli7VMyt0H9EhD1Aoc=,iv:32kEZKOEHfLQa5lNIszSj9S/M/V3DunbnxoxGvDyIzM=,tag:iBS0gMXRSQrv1m0rYRPY+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
