# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:NcpjYiRjvWOtyg==,iv:oE07/Fz5zjVJ1EZ3c3AsBzdJkWeDJVJUOT1a7r162Qk=,tag:gyg4M9Z4mk8N37DoeS1QKQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:KAV2Bqgj3Uf39vdOnDBNpSskOa8mLfAi,iv:2I5TTTYjEpKWlBQzCSOhfZjUHDQSMNq7NLOk/Q3liwI=,tag:BUSHDv6xzs4V7cUxtqsW2g==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ckdvVHMrVDA4THMrOUU3
        cmU3QlJyUXRsRUwvdzlNMW1RbmxOb0Q4UldrClFHcmRKb0RHVUQ2WDBaSjRuUVRr
        NHBzQ2M5NTZvWVpRVU5CckxvUTJZTG8KLS0tIDdHdys4SjdZQU8zejd6ck1kN0E1
        MW85SzVHc2hhdldobkJoWGVkeWcxRFkKA2uG0FagThDJ00He5fAtoNnHktwMrA73
        5GkqYcGzDKhI3GTHNmmcjL0VBuR6bE0l/UgCLDHMFadq2VGegZ+zFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T21:55:36Z"
  mac: ENC[AES256_GCM,data:/MOsg4PkEFD9hUBAWaucTDQ5m95Bt7NdP74hwBRYzR30VenRRVrg+JGrF/Q5UC3OJiZ8x/v9SkbohJIZBGNQapRJuekkvA54jH7Djcw1309pOssRa5rHBFs+0dUiXbqc7YAMnkke7fTX6nbEyqJ+4oixUKIFgXGytIUWH3E7h/k=,iv:I66OoBbKdTyvGxazV72ODgApWyrtzfc9eZWPCs07Vek=,tag:RlOCJBLAUw1q2NjRjdXo4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
