apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:sjYgngP+A8KaUw==,iv:sbKx79TWxmJAl59H74E4Hq9Ui9mqGDDa0JFvRe6dkws=,tag:0qXrIrMvmhcs8wAELumpbg==,type:str]
sops:
    age:
        - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQnlBdWpLM2d4ME5yaTho
            UlZ0SFRsWDFuV2xjYkIvU0VydGtVdDFVL2pFCnFCMkFLYXpSOFNaenlQU1VoTXc1
            c0NST3NGbGhiWHgyTDNrNjVjS1Z4Z2sKLS0tIEpiV1NMc2NPbkExNzRsWEhUaXp1
            WmhlY0lCNnVaUjJkN0l1TTBRSjRxdGcKSvidhyE/xw2tdrqNnO6yvEGYHFy8PL2s
            IC9K0RRSV1Tj5zk20HQvc63Lkwa35q/pJ5FuPwdcPUsLJ/FXJac9mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T21:56:35Z"
    mac: ENC[AES256_GCM,data:NEAqYUUqo/T3JjO1jZ4aueTpuzscgwMzaJFfQ7yo8P5UHUGNI229Gj8/PC43CUusBOZGiEMrjzBP7WcNh1e0Gutw3lCBJvnssHHhMJk/tpDJeRtQ+PePSiANoI9gX85zAiGe7VhAdokYAt38a2s2YaLHSUEFgT+LZb16/ZKFtGk=,iv:faNApk+z3DQXn7wL52en2IiHgsP4QmNI94bEEzQM0gs=,tag:LhCnJVr41GyEYzmEzwd+5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
