apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
    namespace: volsync-system
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:sjYgngP+A8KaUw==,iv:sbKx79TWxmJAl59H74E4Hq9Ui9mqGDDa0JFvRe6dkws=,tag:0qXrIrMvmhcs8wAELumpbg==,type:str]
sops:
    age:
        - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQnlBdWpLM2d4ME5yaTho
            UlZ0SFRsWDFuV2xjYkIvU0VydGtVdDFVL2pFCnFCMkFLYXpSOFNaenlQU1VoTXc1
            c0NST3NGbGhiWHgyTDNrNjVjS1Z4Z2sKLS0tIEpiV1NMc2NPbkExNzRsWEhUaXp1
            WmhlY0lCNnVaUjJkN0l1TTBRSjRxdGcKSvidhyE/xw2tdrqNnO6yvEGYHFy8PL2s
            IC9K0RRSV1Tj5zk20HQvc63Lkwa35q/pJ5FuPwdcPUsLJ/FXJac9mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T23:58:26Z"
    mac: ENC[AES256_GCM,data:MyDEKsE3Ptjzy2Ly9EkrKc0Oo0Fej/xXcxfg48d759GYdLr3V8QGpjAhexaqosrvIw/bBOslZuXl/oWxdNDKaCSgRu0ai5by5rYrofkR6eZ/Mrtiz8YamCSqptgIXuzTclVoRMqFq+9fOceLcNvbRk79jE6yvhi1bld3XKOH4LY=,iv:JmHcSLwlrTi1wqI7QL3fr7KovJ2Q5UQTooR2CN8zY+s=,tag:wxzJpo9OlaSrqvwff9uFCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
